// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbdakkvfedbnpfsfnsrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iZGFra3ZmZWRibnBmc2Zuc3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDYwOTYsImV4cCI6MjA1ODEyMjA5Nn0.ukHhmPfwqk7-Y0brzKG0MMLjEDTH1f7JLozNxyg8eok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);